
DROP TABLE IF EXISTS HIBERNATE_SEQUENCE;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS USER_PROFILE_SETTINGS;
DROP TABLE IF EXISTS SNIFFERS_LOG_SOURCES;
DROP TABLE IF EXISTS SNIFFERS_SCANNER_IDATA;
DROP TABLE IF EXISTS SNIFFERS_EVENTS;
DROP TABLE IF EXISTS SNIFFERS;
DROP TABLE IF EXISTS LOG_SOURCES;

CREATE TABLE IF NOT EXISTS
	LOG_SOURCES (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		NAME VARCHAR(255) NOT NULL,
		CONFIG VARCHAR
	);
CREATE INDEX IF NOT EXISTS LOG_SOURCES_NAME ON LOG_SOURCES(NAME);

CREATE TABLE IF NOT EXISTS
	SNIFFERS (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
        DTYPE VARCHAR(50) NOT NULL,
		NAME VARCHAR(255) NOT NULL,
		CRON_EXPR VARCHAR(50) NOT NULL,
		SOURCE 	BIGINT NOT NULL,
		SCANNER_CONFIG VARCHAR,
		READER_STRATEGY_CONFIG VARCHAR,
		PUBLISHERS_CONFIG VARCHAR
	);
CREATE INDEX IF NOT EXISTS SNIFFERS_NAME ON SNIFFERS(NAME);
CREATE INDEX IF NOT EXISTS SNIFFERS_SOURCE ON SNIFFERS(SOURCE);


CREATE TABLE IF NOT EXISTS
	SNIFFERS_SCHEDULE_INFO (
		SNIFFER	BIGINT NOT NULL,
        schedule_id	BIGINT NOT NULL,
		SCHEDULED BOOLEAN NOT NULL,
		LAST_FIRE TIMESTAMP,
        PRIMARY KEY (SNIFFER, schedule_id),
		FOREIGN KEY(SNIFFER) REFERENCES SNIFFERS(ID)
	);


CREATE TABLE IF NOT EXISTS
	SNIFFERS_SCANNER_IDATA (
		SNIFFER	BIGINT NOT NULL,
		SOURCE 	BIGINT NOT NULL,
		LOG		VARCHAR(512) NOT NULL,
		DATA	VARCHAR	NOT NULL,
		NEXT_POINTER VARCHAR(255) NOT NULL,
		PRIMARY KEY (SNIFFER, SOURCE, LOG),
		FOREIGN KEY(SNIFFER) REFERENCES SNIFFERS(ID),
		FOREIGN KEY(SOURCE) REFERENCES LOG_SOURCES(ID)
	);
CREATE INDEX IF NOT EXISTS SNIFFERS_SCANNER_IDATA_LOG ON SNIFFERS_SCANNER_IDATA(LOG);

/** DEPRECATED **/
CREATE TABLE IF NOT EXISTS
	SNIFFERS_EVENTS (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		SNIFFER			BIGINT NOT NULL,
		SOURCE 			BIGINT NOT NULL,
		LOG				VARCHAR(512) NOT NULL,
		DATA			VARCHAR,
		PUBLISHED 		TIMESTAMP NOT NULL,
		/* ENTRIES			VARCHAR, */
		FOREIGN KEY(SNIFFER) REFERENCES SNIFFERS(ID),
		FOREIGN KEY(SOURCE) REFERENCES LOG_SOURCES(ID)
	);
CREATE INDEX IF NOT EXISTS SNIFFERS_EVENTS_LOG ON SNIFFERS_EVENTS(LOG);
CREATE INDEX IF NOT EXISTS SNIFFERS_EVENTS_PUBLISHED ON SNIFFERS_EVENTS(PUBLISHED);


CREATE TABLE IF NOT EXISTS
	SYSTEM_NOTIFICATIONS (
		SYSTEM_ID VARCHAR(255) NOT NULL PRIMARY KEY,
		NTYPE SMALLINT NOT NULL,
		TITLE VARCHAR NOT NULL,
		MESSAGE VARCHAR,
		LEVEL SMALLINT NOT NULL,
		EXPIRATION TIMESTAMP,
		CREATION TIMESTAMP NOT NULL
	);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_NTYPE ON SYSTEM_NOTIFICATIONS(NTYPE);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_LEVEL ON SYSTEM_NOTIFICATIONS(LEVEL);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_EXPIRATION ON SYSTEM_NOTIFICATIONS(EXPIRATION);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_CREATION ON SYSTEM_NOTIFICATIONS(CREATION);

CREATE TABLE IF NOT EXISTS
	SYSTEM_NOTIFICATIONS_ACKS (
		SYSTEM_ID VARCHAR(255) NOT NULL PRIMARY KEY,
		SYSTEM_USER_NAME VARCHAR(255) NOT NULL,
		FOREIGN KEY(SYSTEM_ID) REFERENCES SYSTEM_NOTIFICATIONS(SYSTEM_ID)
	);
CREATE INDEX IF NOT EXISTS SYSTEM_NOTIFICATIONS_ACKS_USER ON SYSTEM_NOTIFICATIONS_ACKS(SYSTEM_USER_NAME);

CREATE TABLE IF NOT EXISTS
    USER_PROFILE_SETTINGS (
                              TOKEN VARCHAR(255) NOT NULL,
                              PATH VARCHAR(255) NOT NULL,
                              DATA VARCHAR
);
CREATE UNIQUE INDEX IF NOT EXISTS USER_PROFILE_SETTINGS_UNIQUE ON USER_PROFILE_SETTINGS(TOKEN, PATH);
CREATE INDEX IF NOT EXISTS USER_PROFILE_SETTINGS_TOKEN ON USER_PROFILE_SETTINGS(TOKEN);
CREATE INDEX IF NOT EXISTS USER_PROFILE_SETTINGS_PATH ON USER_PROFILE_SETTINGS(PATH);

CREATE TABLE IF NOT EXISTS
    MEMBER (
    ID BIGINT NOT NULL PRIMARY KEY,
    IS_ADMIN BOOLEAN,
    MEMBER_ID VARCHAR(255),
    PASSWORD VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS
    HIBERNATE_SEQUENCE(
    NEXT_VAL BIGINT
);

INSERT INTO HIBERNATE_SEQUENCE (NEXT_VAL) VALUES (0);

